#@TYPE: Machine
#@NAME: cora-z7
#@DESCRIPTION: Baseline support for cora-z7

# Xilinx documentation on machine layers: https://github.com/Xilinx/meta-xilinx/blob/rel-v2024.2/meta-xilinx-core/conf/machine/README

#### Preamble
MACHINEOVERRIDES =. "${@['', 'cora-z7:']['cora-z7' != '${MACHINE}']}"
#### Regular settings follow

require conf/machine/zynq-generic.conf

HDF_URI = "file://cora-z7.xsa"
XILINX_WITH_ESW = "xsct"

# Add pseudodesign linux SD image
# TODO: consider moving this to the distro configuration
# IMAGE_CLASSES += " image-types-pseudo-design"
# IMAGE_FSTYPES += " wic.pseudo-design-sd"
# WKS_FILES = "pseudo-design-linux-sdcard.wks"

# Add pseudodesign linux specific recipes
# TODO: consider moving this to the distro configuration
# IMAGE_INSTALL:append = " pd-data-partition"

#### No additional settings should be after the Postamble
#### Postamble
PACKAGE_EXTRA_ARCHS:append = "${@['', ' cora-z7']['cora-z7' != "${MACHINE}"]}"
