# Add pseudodesign linux SD image
# TODO: consider moving this to the distro configuration
IMAGE_CLASSES += " image-types-pseudo-design"
IMAGE_FSTYPES += " wic.pseudo-design-sd"
WKS_FILES = "pseudo-design-linux-sdcard.wks"

# Add pseudodesign linux specific recipes
# TODO: consider moving this to the distro configuration
IMAGE_INSTALL:append = " pd-data-partition"

# Attach the rootfs disk image to the second SD interface of QEMU (which is SD0)
QB_DEFAULT_FSTYPE_qemuboot-xilinx = "wic.pseudo-design-sd"