# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

LAYERSERIES_COMPAT_pd-xilinx = "scarthgap"

BBFILE_COLLECTIONS += "pd-xilinx"
BBFILE_PATTERN_pd-xilinx = "^${LAYERDIR}/"
BBFILE_PRIORITY_pd-xilinx = "84"

LAYERDEPENDS_pd-xilinx = "mender "

# Recommended for u-boot support for raspberrypi5
# https://git.yoctoproject.org/meta-lts-mixins 'scarthgap/u-boot' branch
LAYERRECOMMENDS_pd-xilinx = "lts-u-boot-mixin"