header:
  version: 14

repos:
  meta-raspberrypi:
    url: https://github.com/agherzan/meta-raspberrypi.git
    commit: 1091bde25e9ebaea33114edb85e4aee931d105f3

  meta-lts-mixins:
    url: https://git.yoctoproject.org/meta-lts-mixins
    commit: a44882db02a0ed0f149371831bfbe067665eb42b
